version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
  postgres:
    image: "postgres"
    container_name: dev-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
