version: "3.9"
services:
  web:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=r2dbc:postgres://dev-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
  postgres:
    image: "postgres"
    container_name: dev-postgres
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/init.sql
